
package dev.noemontes.soapclient.service;

import javax.xml.bind.annotation.XmlSeeAlso;

import dev.noemontes.soapclient.factory.ObjectFactory;
import dev.noemontes.soapclient.model.Country;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryService", targetNamespace = "http://service.soapserver.noemontes.dev/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryService {


    /**
     * 
     * @param arg0
     * @return
     *     returns dev.noemontes.soapclient.generated.Country
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.soapserver.noemontes.dev/CountryService/findByNameRequest", output = "http://service.soapserver.noemontes.dev/CountryService/findByNameResponse")
    public Country findByName(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
